# Cloud Build configuration for automatic deployments
# Triggered by GitHub pushes when connected via Cloud Build

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/dry-guys-damage-restoration-fort-worth:$COMMIT_SHA'
      - '.'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/dry-guys-damage-restoration-fort-worth:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dry-guys-damage-restoration-fort-worth'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/dry-guys-damage-restoration-fort-worth:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--cpu-throttling'

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/dry-guys-damage-restoration-fort-worth:$COMMIT_SHA'

substitutions:
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY
